<?php
session_start();
//SOLO UTILIZA DE UN SOLO LA VARIABLE DEL SESSION START
//O PODEMOS ENCAPSULARLO DIRECTAMENTE YA EN LA VARIABLE BUSQUEDA TUYA
$busqueda=$_SESSION['busqueda'];
//ESTA ES LA PRUEBA QUE FUNCIONA CON EL SESSION BUSQUEDA
//echo 'Prueba '.$_SESSION['busqueda'].'' ; OPCION1 
//O LLAMARLA ASI, AMBAS FORMAS FUNCIONAN
echo 'Prueba '.$busqueda.'' ;//OPCION2 MÁS DIRECTA

?>